spring:
  profiles:
    active: test
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          time_zone : UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    dev:
      platform : postgres
      url : jdbc:postgresql://localhost:5432/hn_marketplace
      username : postgres
      password :
      hikari:
        maximum-pool-size: 5
        minimum-idle: 5
        maxLifetime: 240000
        connection-test-query:  SELECT 1
        idle-timeout: 60000
    test:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testing_db
      username: sa
      password:
      h2:
        console:
          enabled: true

server:
  port: 8080
logging:
  level:
    org:
      hibernate:
        SQL : DEBUG
        type : trace
