spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    name: hn_marketplace
    url : jdbc:postgresql://localhost:5432/hn_marketplace
    username : postgres
    password :
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      maxLifetime: 240000
      connection-test-query:  SELECT 1
      idle-timeout: 60000
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          time_zone : UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres

server:
  port: 8080
logging:
  level:
    org:
      hibernate:
        SQL : DEBUG
        type : trace