spring:
  profiles: dev
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          time_zone : UTC
  #      database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  datasource:
    platform : postgres
    url : jdbc:postgresql://localhost:5432/hn_marketplace
    username : postgres
    password :
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      maxLifetime: 240000
      connection-test-query:  SELECT 1
      idle-timeout: 60000

server:
  port: 8080
logging:
  level:
    org:
      hibernate:
        SQL : DEBUG
        type : trace
